name: CI/CD Pipeline automated build docker & deploy by Auroraphtgrp01

on:
  push:
    branches:
      - for-deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Bun Install & build
        run: |
          bun install --frozen-lockfile
          bunx prisma generate
          bun run build

      - name: Build Docker image
        run: docker compose build

      - name: Push Docker image
        run: docker compose push

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/hz
            docker ps -q --filter "ancestor=auroraphtgrp/sns-api:latest" | xargs -r docker stop
            docker ps -aq --filter "ancestor=auroraphtgrp/sns-api:latest" | xargs -r docker rm
            docker rmi auroraphtgrp/sns-api:latest
            docker compose up -d

      - name: CI/CD Workflow Info
        run: |
          echo "CI/CD Workflow by Minh Tuan Le (auroraphtgrp01)"
          echo "Workflow completed successfully!" 