networks:
  sns-network:
    name: 'sns-network'
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/16
          ip_range: 10.0.0.0/24
          gateway: 10.0.0.1

services:
  sns-api:
      image: auroraphtgrp/sns-new-api:latest
      container_name: sns-new-api
      build:
        context: .
        dockerfile: Dockerfile
      networks:
        - sns-network
      ports:
        - "9930:9933"
      command: sh -c "npx prisma db push && node dist/main.js"
      environment:
        - NODE_ENV=development
        - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/sns-dev-1?schema=public
        - PORT=9933
        - SMS_HOST=https://sms.vivas.vn/SMSBNAPINEW
        - SMS_USERS_KEY=cohed
        - SMS_PASS_SECRET="cohed@#2025"
        - SMS_BRANDNAME=SafeNSound
        - SMS_ISUNICODE=0
        - FRONTEND_URL=localhost:3000
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - REDIS_PASSWORD=redis
        - JWT_VERIFY_TOKEN_SECRET_KEY=key
        - COOKIE_SECRET=key
        - JWT_REFRESH_TOKEN_EXPIRATION_TIME=30d
        - JWT_REFRESH_TOKEN_SECRET_KEY=key
        - JWT_ACCESS_TOKEN_EXPIRATION_TIME=30d
        - JWT_ACCESS_TOKEN_SECRET_KEY=key
        - JWT_VERIFY_TOKEN_EXPIRATION_TIME=30d
      restart: unless-stopped
      depends_on:
        postgres:
          condition: service_healthy
        redis:
          condition: service_healthy

  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres-5439-sns-prod
    networks:
      - sns-network
    volumes:
      - postgres-data-be:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=sns
    ports:
      - '5439:5432'
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'

  redis:
    container_name: redis-6444-sns-prod
    image: bitnami/redis:latest
    networks:
      - sns-network
    ports:
      - '6444:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
    volumes:
      - redis-data:/bitnami/redis
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'redis-cli', '--raw', 'ping' ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
volumes:
  postgres-data-be:
  redis-data: